USE [master]
GO

/****** Object:  Database [Almacen]    Script Date: 04/02/2013 20:08:29 ******/
CREATE DATABASE [Almacen] ON  PRIMARY 
( NAME = N'Almacen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Almacen.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Almacen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Almacen_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Almacen] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Almacen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Almacen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Almacen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Almacen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Almacen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Almacen] SET ARITHABORT OFF 
GO

ALTER DATABASE [Almacen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Almacen] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Almacen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Almacen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Almacen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Almacen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Almacen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Almacen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Almacen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Almacen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Almacen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Almacen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Almacen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Almacen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Almacen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Almacen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Almacen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Almacen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Almacen] SET  READ_WRITE 
GO

ALTER DATABASE [Almacen] SET RECOVERY FULL 
GO

ALTER DATABASE [Almacen] SET  MULTI_USER 
GO

ALTER DATABASE [Almacen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Almacen] SET DB_CHAINING OFF 
GO

